# Generated by Django 4.1.7 on 2023-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photo/default.jpg', null=True, upload_to='profile_photo'),
        ),
    ]
